# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  # makes classes in src/AppBundle/DataFixtures available to be used as services
  # and have a tag that allows actions to type-hint services
  AppBundle\DataFixtures\:
    resource: '../../src/AppBundle/DataFixtures'
    tags: ['doctrine.fixture.orm']